from django.conf import settings
from django.db import migrations, models
import django.core.validators
import django.db.models.deletion
from django.db.models import Q

class Migration(migrations.Migration):
    initial=True
    dependencies=[migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
        migrations.CreateModel(name='Profile',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('role',models.CharField(choices=[('owner','Property Owner'),('tenant','Tenant')],default='tenant',max_length=10)),('phone',models.CharField(blank=True,max_length=30)),('address',models.CharField(blank=True,max_length=255)),('user',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='profile',to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='Property',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('title',models.CharField(max_length=200)),('description',models.TextField()),('property_type',models.CharField(choices=[('Apartment','Apartment'),('House','House'),('Room','Room'),('Office','Office')],max_length=20)),('location',models.CharField(max_length=255)),('monthly_rent',models.DecimalField(decimal_places=2,max_digits=12)),('bedrooms',models.PositiveIntegerField(default=1)),('bathrooms',models.PositiveIntegerField(default=1)),('image',models.ImageField(blank=True,null=True,upload_to='properties/')),('availability_status',models.CharField(choices=[('available','Available'),('rented','Rented'),('unavailable','Unavailable')],default='available',max_length=20)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('owner',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='properties',to=settings.AUTH_USER_MODEL))],options={'ordering':['-created_at']}),
        migrations.CreateModel(name='RentalRequest',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('message',models.TextField()),('request_date',models.DateTimeField(auto_now_add=True)),('status',models.CharField(choices=[('pending','Pending'),('accepted','Accepted'),('rejected','Rejected'),('cancelled','Cancelled')],default='pending',max_length=20)),('property',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='rental_requests',to='rental.property')),('tenant',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='rental_requests',to=settings.AUTH_USER_MODEL))],options={'ordering':['-request_date']}),
        migrations.CreateModel(name='Review',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('rating',models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1),django.core.validators.MaxValueValidator(5)])),('comment',models.TextField()),('created_at',models.DateTimeField(auto_now_add=True)),('property',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='reviews',to='rental.property')),('tenant',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='reviews',to=settings.AUTH_USER_MODEL))]),
        migrations.AddConstraint(model_name='rentalrequest',constraint=models.UniqueConstraint(condition=Q(status='pending'),fields=('property','tenant'),name='unique_pending_request_per_tenant_property')),
        migrations.AddConstraint(model_name='review',constraint=models.UniqueConstraint(fields=('property','tenant'),name='one_review_per_tenant_property')),
    ]
